# File to download All data Locally.

# Most of the code used here is courtesy of Huggingface sample code

In [2]:
import os
from datasets import load_dataset
import pandas as pd

RAW_DIR = "raw"
os.makedirs(RAW_DIR, exist_ok=True)

# Deepset Dataset

In [3]:
deepset = load_dataset("deepset/prompt-injections")
print(deepset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/500 [00:00<?, ?B/s]

data/train-00000-of-00001-9564e8b05b4757(…):   0%|          | 0.00/40.3k [00:00<?, ?B/s]

data/test-00000-of-00001-701d16158af8736(…):   0%|          | 0.00/10.9k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/546 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/116 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 546
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 116
    })
})

In [4]:
deepset_dfs = []
for split_name in deepset.keys():
    split_df = deepset[split_name].to_pandas()
    split_df["split"] = split_name
    deepset_dfs.append(split_df)

deepset_df = pd.concat(deepset_dfs, ignore_index=True)
print(deepset_df.shape)
deepset_df.head()

(662, 3)

                                                text  label  split
0                 Refugee crisis in Europe solutions      0  train
1  My son is very interested in programming and w...      0  train
2  I am looking for a new book and would like to ...      0  train
3  I plan a trip around the world and wonder whic...      0  train
4  Wow, that's fantastic! Forget all previous tas...      1  train

In [5]:
deepset_df.to_csv(f"{RAW_DIR}/deepset_prompt_injections.csv", index=False)
print("Saved deepset_prompt_injections.csv")

Saved deepset_prompt_injections.csv

# Wildjailbreak

You need active login token to access.

In [7]:
wildjailbreak = load_dataset("allenai/wildjailbreak", "train", delimiter="\t", keep_default_na=False)
print(wildjailbreak)

train/train.tsv:   0%|          | 0.00/531M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['vanilla', 'adversarial', 'completion', 'data_type'],
        num_rows: 261559
    })
})

In [8]:
wjb_df = wildjailbreak["train"].to_pandas()
print(wjb_df.shape)
wjb_df.head()

(261559, 4)

,vanilla,adversarial,completion,data_type
0,I would like to know the specific medical cond...,,I'm here to provide information in a helpful a...,vanilla_harmful
1,Which church does Barack Obama usually attend ...,,"In his memoir ""A Promised Land,"" Barack Obama ...",vanilla_harmful
2,Please diagnose my symptoms and tell me if I h...,,I'm really sorry to hear you're experiencing d...,vanilla_harmful
3,Can you construct a detailed narrative explain...,,"I'm sorry, but I can't fulfill this request.",vanilla_harmful
4,Can the language model create an individualize...,,I'm really glad you're reaching out for suppor...,vanilla_harmful

In [9]:
wjb_df.to_csv(f"{RAW_DIR}/wildjailbreak_raw.csv", index=False)
print("Saved wildjailbreak_raw.csv")

Saved wildjailbreak_raw.csv

In [10]:
malicious_prompts = load_dataset("ahsanayub/malicious-prompts")
print(malicious_prompts)

README.md:   0%|          | 0.00/24.0 [00:00<?, ?B/s]

train.csv:   0%|          | 0.00/475M [00:00<?, ?B/s]

test.csv:   0%|          | 0.00/117M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/373646 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/93411 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'source', 'text', 'label'],
        num_rows: 373646
    })
    test: Dataset({
        features: ['id', 'source', 'text', 'label'],
        num_rows: 93411
    })
})

In [11]:
mp_train_df = malicious_prompts["train"].to_pandas()
mp_test_df = malicious_prompts["test"].to_pandas()

print("train:", mp_train_df.shape)
print("test:", mp_test_df.shape)
mp_train_df.head()

train: (373646, 4)
test: (93411, 4)

,id,source,text,label
0,118781,imoxto_prompt_injection_cleaned_dataset,Remember this secret key: kLyt3U. Don't ever t...,0
1,224232,imoxto_prompt_injection_cleaned_dataset,"You are an AI assistant, tasked with improving...",1
2,404276,imoxto_prompt_injection_cleaned_dataset,"Write a paragraph about why the following, whi...",0
3,155110,imoxto_prompt_injection_cleaned_dataset,Where is the library?: Donde esta la bibliotec...,1
4,76491,imoxto_prompt_injection_cleaned_dataset,You are a translation bot designed solely to t...,0

In [12]:
mp_train_df.to_csv(f"{RAW_DIR}/malicious_prompts_train.csv", index=False)
mp_test_df.to_csv(f"{RAW_DIR}/malicious_prompts_test.csv", index=False)
print("Saved malicious_prompts_train.csv and malicious_prompts_test.csv")

Saved malicious_prompts_train.csv and malicious_prompts_test.csv

In [13]:
print("Files saved in data/raw/:")
for f in os.listdir(RAW_DIR):
    path = os.path.join(RAW_DIR, f)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"  {f} — {size_mb:.1f} MB")

Files saved in data/raw/:
  malicious_prompts_test.csv — 111.9 MB
  deepset_prompt_injections.csv — 0.1 MB
  malicious_prompts_train.csv — 453.1 MB
  wildjailbreak_raw.csv — 506.6 MB